services:
  homepage:
    build: .
    ports:
      - "5000:4000"
    pid: host
    volumes:
      - /sys:/sys:ro
      - /:/hostfs:ro
      - ./data/services.json:/app/data/services.json
    environment:
      - HOST_FS=/hostfs
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REFRESH_TOKEN=${GOOGLE_REFRESH_TOKEN}
      - GOOGLE_CALENDAR_ID=${GOOGLE_CALENDAR_ID}
    restart: unless-stopped
